snyk/go-application-framework

- Makefile
- go.mod
- go.sum
- pkg/configuration/configuration.go
- pkg/configuration/configuration_test.go
- pkg/workflow/configurationoptionsimpl.go
- pkg/workflow/dataimpl.go
- pkg/workflow/engine_test.go
- pkg/workflow/engineimpl.go
- pkg/workflow/entryimpl.go
- pkg/workflow/invocationcontextimpl.go
- pkg/workflow/types.go
Implement the initial version of the WorkflowEngine
> Feat: Introduce workflow engine

- pkg/analytics/analytics.go
- pkg/analytics/analytics_test.go
Fix incorrect endpoint name and adapt test to catch similar issues in the future
> fix: analytics api endpoint

- go.mod
- go.sum
- pkg/app/app.go
- pkg/configuration/configuration.go
- pkg/configuration/configuration_test.go
- pkg/configuration/constants.go
- pkg/local_workflows/depgraph_workflow.go
- pkg/local_workflows/local_workflows.go
- pkg/local_workflows/output_workflow.go
- pkg/networking/api_tokens.go
- pkg/networking/networking.go
- pkg/workflow/dataimpl.go
- pkg/workflow/engine_test.go
- pkg/workflow/engineimpl.go
- pkg/workflow/invocationcontextimpl.go
- pkg/workflow/types.go
Add local extension workflows depgraph and output.
On the way:
* extended Configuration: added cloning and additional data types
* extended Workflow: introduced default logger 
* add common initialization via app package
> Extend application framework and introduce default local extensions

- pkg/mocks/networking.go
- pkg/networking/certs/certs.go
- pkg/networking/certs/certs_test.go
- pkg/networking/networking.go
- pkg/networking/networking_test.go
Support adding additional CA Certificates to NetworkAccess from a given PEM file.
* moved "certs" functionality from CLI repo over
* integrated adding additional CA Certificates from a PEM file
> Support adding additional CA Certificates to NetworkAccess

- internal/utils/file.go
- pkg/analytics/analytics.go
- pkg/utils/array.go
- pkg/utils/array_test.go
* update (from cli repo) and move array internal/utils to pkg/utils
* cleanup some unused things
> Add Merge() of string slices

- pkg/analytics/analytics.go
- pkg/app/app.go
- pkg/configuration/configuration.go
- pkg/local_workflows/depgraph_workflow.go
- pkg/local_workflows/local_workflows.go
- pkg/local_workflows/output_workflow.go
- pkg/networking/api_tokens.go
- pkg/networking/certs/certs.go
- pkg/networking/networking.go
- pkg/utils/array.go
- pkg/workflow/configurationoptionsimpl.go
- pkg/workflow/dataimpl.go
- pkg/workflow/engineimpl.go
- pkg/workflow/entryimpl.go
- pkg/workflow/invocationcontextimpl.go
- pkg/workflow/types.go
**What does this PR do?**
This PR should enrich the documentation for all packages under the public API`pkg/`
> enrich documentation [HEAD-35]

- pkg/app/app.go
- pkg/configuration/constants.go
- pkg/local_workflows/local_workflows.go
Use a central configuration value to make oauth available or not, default is disabled.
> chore: use config value to disable oauth changes

- pkg/auth/oauth2authenticator.go
> fix: change config key to avoid name conflict

- pkg/networking/networking.go
Append default headers to requests if not set.
> fix: appropriately set default headers if undefined

- pkg/local_workflows/auth_workflow.go
Using the same message as the regular auth flow
> chore: add console message to oauth auth

- pkg/analytics/analytics.go
- pkg/analytics/analytics_test.go
Before sending Analytics data, we redact sensitive data. With a new additional command line argument format we support, we need to adapt the filtering of this format as well `--key value`. In addition this PR adds some more sensitive field values to ensure that everything is captured.
> feat: Improve analytics filtering

- pkg/auth/oauth2authenticator.go
Changes the message when authentication fails, so that IntelliJ can parse it.
> chore: change authentication failed message [HEAD-115]

- pkg/configuration/configuration.go
Synchronize get and set on a configuration object to allow thread-safe access.
> feat: add minimal locking to configuration

- pkg/app/app.go
- pkg/app/app_test.go
- pkg/auth/authenticator.go
- pkg/auth/oauth2authenticator.go
- pkg/auth/oauth2authenticator_test.go
- pkg/auth/oauth2authenticatoroptions.go
- pkg/local_workflows/auth_workflow.go
- pkg/networking/networking_test.go
avoid issues when concurrently trying to refresh the oauth token
> feat: synchronize oauth token refresh

- pkg/auth/oauth2authenticator.go
- pkg/configuration/configuration.go
- pkg/configuration/configuration_test.go
fixes clone of configurations with custom storage
> fix: clone configuration

- pkg/local_workflows/depgraph_workflow.go
- pkg/local_workflows/depgraph_workflow_test.go
Adds support for the `exclude` flag in the dep graph workflow.
> feat(LINK-301): adds exclude flag

- pkg/app/app.go
- pkg/app/app_test.go
[JIRA ticket](https://snyksec.atlassian.net/browse/HEAD-274)
Enable OAuth Feature Flag based on endpoint configuration.
> feat: enable OAuth FF based on endpoint config

- pkg/networking/useragent.go
- pkg/networking/useragent_test.go
This PR removes the newline in the User Agent
HEAD-562
> fix: sanitise user agent string representation [HEAD-562]

- pkg/configuration/constants.go
Adding new and changing existing internal config key
> chore: add & adapt internal config keys

- pkg/configuration/constants.go
> feat: introduce unknown args

- pkg/auth/oauth2authenticator.go
- pkg/auth/tokenauthenticator.go
- pkg/networking/networking_test.go
As a temporary workaround introduce the Session-Token Header
> feat: temporarily add legacy Session-Token [HEAD-884]

- pkg/mocks/networking.go
- pkg/networking/networking.go
- pkg/workflow/engine_test.go
- pkg/workflow/engineimpl.go
> fix: missing assignment of config and logger after set

- pkg/local_workflows/report_analytics_workflow.go
- pkg/local_workflows/report_analytics_workflow_test.go
**Description**
This PR returns an error when `gojsonschema.Validate` fails.
HEAD-1030
> refactor: return error when validating json [HEAD-1030]

- internal/api/urls.go
- internal/api/urls_test.go
- pkg/configuration/configuration.go
- pkg/configuration/configuration_test.go
- pkg/mocks/configuration.go
- pkg/utils/array.go
also improve IP address handling when canonicalizing API URLs.
> feat: improved configuration handling to enable checking if values are set or not

- Makefile
- pkg/configuration/constants.go
- pkg/local_workflows/json_schemas/schemas.go
- pkg/local_workflows/report_analytics_workflow.go
- pkg/local_workflows/report_analytics_workflow_test.go
- pkg/local_workflows/whoami_workflow.go
- changed command to "analytics report"
- changed deviceId to device_id in json payload/schema
- added --experimental flag and enforce usage of it
> refactor: rename reportsAnalytics command workflow

- pkg/logging/scrubbingLogWriter.go
- pkg/logging/scrubbingLogWriter_test.go
- pkg/networking/networking.go
- feat: introduce helper for configuration object
- refactor: drop seperate scrubbing logic
> feat: introduce helper for configuration object

- pkg/local_workflows/json_schemas/data_test_summary.go
- pkg/workflow/constants.go
- pkg/workflow/json_schemas/data_test_summary.go
Document the schema and content type for extensions to use when outputting test results.
> feat: introduce test summary schema

- internal/presenters/__snapshots__/presenter_sarif_results_pretty_test.snap
- internal/presenters/presenter_sarif_results_pretty_test.go
- internal/presenters/styles.go
Small fix here correctly the appearance of Medium severity vulns in Light mode.
> fix: correct colour code for medium severity

- pkg/logging/scrubbingLogWriter.go
- pkg/logging/scrubbingLogWriter_test.go
add additional known strings to the logger redact patterns
> feat(logging): add additional redact pattern

- pkg/logging/scrubbingLogWriter.go
- pkg/logging/scrubbingLogWriter_test.go
increase character count for matching sensitive data to reduce false positive matches like single character
> fix: improve logger redact pattern

- go.mod
- go.sum
- internal/utils/sarif/sarif.go
- pkg/local_workflows/code_workflow/native_workflow.go
- pkg/local_workflows/code_workflow_test.go
- pkg/local_workflows/json_schemas/data_test_summary.go
- pkg/local_workflows/output_workflow.go
- pkg/local_workflows/output_workflow_test.go
- pkg/workflow/dataimpl.go
- pkg/workflow/dataimpl_test.go
- pkg/workflow/types.go
> feat: introduce error annotations for data objects [CLI-309]

- pkg/local_workflows/code_workflow/native_workflow.go
- pkg/local_workflows/code_workflow_test.go
The screenshot shows how it looks like, when integrated in the CLI.
> feat: adapt gaf progressbar to code client progress tracker

- pkg/app/app.go
- pkg/app/app_test.go
- pkg/configuration/constants.go
- pkg/local_workflows/auth_workflow.go
- pkg/local_workflows/auth_workflow_test.go
* Added configuration.PREVIEW_FEATURES_ENABLED to determine based on the runtime version, if preview features are enabled.
* use configuration.PREVIEW_FEATURES_ENABLED to enable OAuth authentication by default
> feat: introduce a possibility to determine if preview features shall be enabled

- go.mod
- go.sum
- pkg/configuration/configuration.go
- pkg/configuration/configuration_test.go
- pkg/configuration/storage.go
- pkg/local_workflows/config_workflow.go
- pkg/mocks/configuration.go
* to inform users that the configuration might be inconsistent
> feat: add configuration sanity check to configuration environment workflow

- pkg/logging/scrubbingLogWriter.go
Before this PR, iterating over the scrub word dict was not protected from writes to the dict via addTerm() or removeTerm(). I've added a RWMutex to allow unlimited iterating over the dict, but locking everything once a write is occurring. This should fix concurrency issues like in https://github.com/snyk/snyk-ls/actions/runs/10162805720/job/28104241006?pr=608
> fix: use RWMutex to allow sync writes/reads on dict for scrub writer

- go.mod
- go.sum
- pkg/local_workflows/config_workflow.go
> cli-431 add final environment mappings

- pkg/local_workflows/network_utils/snyk_request_id.go
- pkg/local_workflows/network_utils/snyk_request_id_test.go
- pkg/mocks/networking.go
- pkg/networking/networking.go
- pkg/networking/networking_test.go
* This PR adds a possibility to add http headers dynamically in addition to the existing static headers.
* It also introduces a helper to add a dynamically generated snyk-request-id
> feat: Add support for dynamic headers

- pkg/workflow/engine_test.go
- pkg/workflow/engineimpl.go
Fixes a data race discovered in concurrent execution of engine.Invoke and variants.
> fix: mutex on increment invocation counter

- internal/api/api.go
- internal/api/api_test.go
- pkg/app/app.go
- pkg/app/app_test.go
- pkg/local_workflows/code_workflow.go
- pkg/local_workflows/code_workflow_test.go
- pkg/local_workflows/config_utils/feature_flag.go
* helper function to register feature flag
* move existing functionality to use helper.
> chore: introduce helper function to register a feature flag accessible via the configuration

- .circleci/config.yml
Enhance build efficiency by implementing CircleCI caching for GolangCI-Lint.
* **Benefits:** Reduced build times, improved resource utilization, and faster feedback loops.
* **Key Features:** Caching of dependencies and intermediate results.
* **Implementation:** Configured `.circleci/config.yml` to cache relevant directories and optimized GolangCI-Lint settings.
* **Expected Outcomes:** Significant reduction in build durations and improved developer experience.
Observations:
* [First build](https://app.circleci.com/pipelines/github/snyk/go-application-framework/1490/workflows/1db8c1b3-fc9c-4bb7-880b-270b06929475), `Lint` step took 1m33s 
* Subsequent build, `Restore cache` + `Lint` steps took 11s
Note: These observations were made on repeated runs against the same commit so represents …
> chore(ci): adopt cache for golangci

- internal/utils/findings/findings.go
- pkg/local_workflows/filter_workflow.go
- pkg/local_workflows/filter_workflow_test.go
- Ensured that the summary results are updated correctly after filtering the findings.
- Test case to check summary matches findings
> chore: update summary after filter

- pkg/local_workflows/config_workflow.go
- pkg/local_workflows/config_workflow_test.go
[CLI-568]
[CLI-568]: https://snyksec.atlassian.net/browse/CLI-568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: support URL to Region Alias

- go.mod
- go.sum
- internal/cueutils/source/openapi/rest/generated.txt
- internal/cueutils/source/openapi/rest/test.spec.yaml
- pkg/local_workflows/data_transformation_workflow.go
- pkg/local_workflows/data_transformation_workflow_test.go
- pkg/local_workflows/local_models/models.gen.go
- pkg/local_workflows/testdata/sarif-snyk-goof-ignores.json
- pkg/local_workflows/testdata/single-result.json
This pull request includes a cleanup of dependencies, enhancements to the data transformation workflow, and the addition of new fingerprint types. These will automatically get rendered as part of our [SARIF output template](https://github.com/snyk/go-application-framework/blob/c8bc6fbe1129b5269db5060d483410e8075b701f/internal/presenters/templates/local_finding.sarif.tmpl#L119)
* Updated `github.com/snyk/code-client-go` from v1.12.0 to v1.13.0 in `go.mod`.
* Removed several unused dependencies from `go.mod` to clean up the project. [[1]](diffhunk://#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L29) [[2]](diffhunk://#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L42-L54) [[3]](diffhunk://#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec071671 …
> chore: transform new fingerprints

- go.mod
- go.sum
- pkg/local_workflows/code_workflow/native_workflow.go
- pkg/local_workflows/code_workflow/native_workflow_test.go
- pkg/local_workflows/code_workflow_test.go
* This PR enables to code test individual files in addition to folders.
* The Code-Client-Go update is not necessary but helpful.
> feat: Support single file code test

- internal/presenters/__snapshots__/components_test.snap
- internal/presenters/components.go
- internal/presenters/components_test.go
- pkg/ui/__snapshots__/consoleui_test.snap
Adjust how white space is added around error object. 
* Missing no status code test: Adds a case for errors without a status code, preventing display issues and ensuring the message is still shown correctly. This is particularly important for certain error types where a status code might not be available.
* Improved layout: Adjusts the layout of error details, making the information more clearly presented.
> fix: add line break below description/detail

- pkg/mocks/configuration.go
- pkg/mocks/networking.go
> fix: regenerate mocks for configuration and networking

- go.mod
- go.sum
Include https://github.com/snyk/code-client-go/pull/96
> fix: Fix hash mismatch when uploading binaries

- pkg/local_workflows/config_utils/feature_flag.go
Providing an additional helper function to access feature flags.
related to #322
> chore: add helper to access feature flags

- pkg/apiclients/testapi/testapi.go
- pkg/apiclients/testapi/testapi_test.go
What this does:
- adds functional options to the Test Client (high level unified test API).
- the low-level oapicodegen API already has functional options, so the high-level API wraps them. They're accumulated and passed internally to oapi.gen.go
> feat: [DGP-351] support functional options in Test Client

- pkg/logging/scrubbingLogWriter.go
- pkg/logging/scrubbingLogWriter_test.go
Add scrubbing of basic auth information from debug logs
> fix: Add scrubbing of basic auth headers

- pkg/local_workflows/connectivity_check_extension/README.md
- Document workflow ID and content types
- Rename options to Flags; confirm defaults
- Correct status strings (DNS ERROR, TLS/SSL ERROR)
- Note default org formatting
- Include proxyConfig.noProxy in JSON example
- Clarify CLI example: snyk tools connectivity-check --json --experimental
> docs(connectivity-check): align README with implementation

- go.mod
- go.sum
- internal/presenters/templates/local_finding.sarif.tmpl
- pkg/local_workflows/code_workflow/native_workflow.go
- pkg/local_workflows/local_models/transform.go
- pkg/local_workflows/output_workflow_test.go
- pkg/local_workflows/testdata/sarif-snyk-goof-ignores.json
> chore: merge `release/1.1299` back into `main`
