pkg/analytics/analytics.go, pkg/networking/networking.go, pkg/networking/networking_test.go, pkg/workflow/engineimpl.go
use go-httpauth to support advanced proxy authentication mechanism within the networking package per default.
=> chore: use ProxyAuthentication from go-httpauth

internal/utils/cache-dir.go
Return “snyk” instead of empty string, to be used later as the cache directory name.
=> chore: return snyk instead of empty string

internal/constants/constants.go, pkg/app/app.go
* When accessing the configured API_URL, consider the 'endpoint' value configured in the snyk.json file
* adapted default API_URL
=> Fix: add endpoint alias when reading API Url configuration

pkg/utils/array_test.go
Ensure to sort string slices before comparing them since one is based on a map and has random ordering.
=> chore: sort before comparison to fix flaky test

pkg/local_workflows/output_workflow.go, pkg/local_workflows/output_workflow_test.go
This PR adds support for unknown mime types which are convertible to string by default, so that they are displayed on the console as if they would be text/plain.
=> feat: Handle additional mime types in output module

internal/api/api.go, internal/api/api_test.go, pkg/app/app.go, pkg/app/app_test.go
- Fix wrong API url path when querying for fetching org from a slug.
- Default to user default org, when org derivation from slug fails.
=> fix: org derivation when existing value provided [HEAD-137]

pkg/app/app.go, pkg/app/app_test.go, pkg/auth/authenticator.go, pkg/auth/authenticator_test.go, pkg/auth/oauth2authenticator.go, pkg/configuration/configuration.go, pkg/configuration/configuration_test.go, pkg/configuration/constants.go, pkg/local_workflows/local_workflows.go, pkg/mocks/configuration.go, pkg/networking/networking_test.go
This PR should ensure that api token environment variables override what is stored in a configuration file of the CLI.
This should mean that the OAuth flow should be skipped if an OAuth token env var is provided, even if the OAuth flow feature flag is enabled in the config.
=> chore: handle token specified via env var [HEAD-156]

pkg/networking/networking.go
To ensure that an http client always uses the correct authenticator, this PR removes caching of the authenticator.
=> chore: remove caching of authenticator

pkg/auth/oauth2authenticator.go
To support multiple Authorization attempts via OAuth e.g. from IDEs, use a custom Multiplexer.
=> feat: support multiple OAuth authentications

pkg/app/app.go, pkg/app/app_test.go, pkg/auth/authenticator.go, pkg/auth/oauth2authenticator.go, pkg/auth/oauth2authenticator_test.go, pkg/auth/oauth2authenticatoroptions.go, pkg/local_workflows/auth_workflow.go, pkg/networking/networking_test.go
- creates an option based constructor with defaults
- makes all other constructors use it
- deprecates previous custom constructors
- Dependent on https://github.com/snyk/go-application-framework/pull/51 (should be merged onto that branch/PR)
=> feat: Introduce functional options for OAuthAuthenticator

go.mod, go.sum, internal/utils/zerologConverter.go, pkg/app/app.go, pkg/app/app_test.go, pkg/app/options.go, pkg/mocks/networking.go, pkg/mocks/workflow.go, pkg/networking/middleware/proxy_config.go, pkg/networking/networking.go, pkg/workflow/engineimpl.go, pkg/workflow/invocationcontextimpl.go, pkg/workflow/types.go
* using zerolog as a more feature rich logger makes generally sense, in addition to the fact that snyk-ls uses it as well
* At some places we are keeping both log.Logger and zerolog.Logger for backwards compatibility
=> feat: introduce zerolog to better integrate with LS

pkg/app/app.go, pkg/app/app_test.go
As we learned some of the configuration defaults and alternative keys are more specific for the CLI use case, therefore we moved them into the CLI repo and make this application framework more use case agnostic.
=> chore: move configuration defaults … to cli

pkg/local_workflows/depgraph_workflow.go, pkg/local_workflows/depgraph_workflow_test.go
This PR adds the `--detection-depth` and `--prune-repeated-subdependencies` flags for `depGraph` workflow.
=> feat: add additional flags for depGraph workflow

pkg/local_workflows/depgraph_workflow.go, pkg/local_workflows/depgraph_workflow_test.go
This forwards the `--debug` flag to the `legacycli` workflow when being called in the `depgraph` workflow.
=> fix: forward --debug flag in depgraph workflow

pkg/local_workflows/depgraph_workflow.go, pkg/local_workflows/depgraph_workflow_test.go
In order to support sbom generation for maven including dev-dependencies we need to add support to pass the dev flag to the cli. See jira ticket for more info.
[JIRA](https://snyksec.atlassian.net/browse/SUP-1187)
=> fix: added support for dev flag

pkg/configuration/constants.go
Currently all Environment Variables are used when looking up config values. This can lead to conflicts when a TOKEN and SNYK_TOKEN environment variable is existing, as TOKEN is the first key to be looked up.
=> fix: rename config key for auth token to avoid collisions

pkg/configuration/constants.go
Currently we do not identify all Snyk/GAF specific bearer token environment variable, this can lead to issues where a bearer_token env var is used by the client for non-snyk purposes. This PR uses the Snyk specific bearer_token env var to avoid this.
=> fix: generic bearer_token name to avoid collisions

pkg/app/app_test.go, pkg/configuration/constants.go, pkg/networking/fips/fips_crypto.go, pkg/networking/fips/fips_crypto_test.go, pkg/networking/fips/non_fips_crypto.go, pkg/networking/fips/non_fips_crypto_test.go
* Enable reading the fips status/configuration via the configuration package
* Implement conditional compiling fips package that enables to detect if fips is available and validates a given config
* Boy Scout Rule: use in-memory config in some tests that weren't using it before
=> feat: support fips configuration and validation

internal/api/urls.go, internal/api/urls_test.go
This change prevents `stella:8000` redirecting to use `api.stella:8000`. This is needed to allow developers to successfully configure their snyk cli instance to communicate with their stella environment.
=> feat: prevent stella:8000 redirecting to api.stella:8000

pkg/app/app.go, pkg/app/app_test.go, pkg/networking/networking.go, pkg/networking/networking_test.go, pkg/workflow/engineimpl.go
Some of the pre-configured HTTP clients were missing the configured default headers.
=> fix: missing default HTTP headers [HEAD-936]

go.mod, go.sum, pkg/local_workflows/json_schemas/scan_done_analytics_event.json, pkg/local_workflows/json_schemas/schemas.go, pkg/local_workflows/local_workflows.go, pkg/local_workflows/report_analytics_workflow.go, pkg/local_workflows/report_analytics_workflow_test.go, pkg/local_workflows/test_utils.go, pkg/local_workflows/whoami_workflow.go, pkg/local_workflows/whoami_workflow_test.go
We added a new extension that can report analytics data for the "Scan done" event type to the Snyk REST API at `"/rest/api/orgs/"+orgId+"/analytics"`.
Input is validated against the committed JSON Schema which is derived from the Open API spec agreed on between implementing teams.
=> feat: add report analytics extension [HEAD- 879]

pkg/configuration/constants.go, pkg/networking/middleware/auth_header.go, pkg/networking/middleware/auth_header_test.go
Introduce on optional configuration to specify additional URLs for which authentication header are being added.
=> fix: support additional URLs for authentication [HEAD-1017]

pkg/configuration/configuration.go, pkg/configuration/configuration_test.go, pkg/mocks/configuration.go
Enable to get configuration values and determine if the retrieved value was explicitly set or not
=> feat: introduce GetAndIsSet() to determine if [HEAD-1031]

pkg/local_workflows/report_analytics_workflow.go, pkg/local_workflows/report_analytics_workflow_test.go
This enables `snyk reportAnalytics -i '<json-data>'`. This extension is not meant for public consumption.
=> feat: accept cli input for report analytics [HEAD-921]

pkg/configuration/configuration.go, pkg/configuration/configuration_test.go
Fix previously introduced error when looking up configuration values via alternative keys. when there where multiple alternative keys, a successful lookup could get overridden by a later alternative key.
=> fix: alternate key usage

pkg/configuration/constants.go
Adding a configuration key for setting a maximum timeout the user is willing to wait for a snyk command to execute.
=> feat: snyk_timeout_secs configuration key

pkg/app/app.go, pkg/app/app_test.go, pkg/auth/oauth2authenticator.go, pkg/auth/oauth2authenticator_test.go, pkg/local_workflows/auth_workflow.go
This PR adds OAuth [Client Credentials Grant](https://datatracker.ietf.org/doc/html/rfc6749#section-4.4) to the OAuth2Authenticator, in addition to the existing Authorization Code Grant. It therefore switches between these types, per default it'll continue to use Authorization Code Grant and if Client ID and Client Secret are configured, it'll use the Client Credentials Grant.
=> feat: support OAuth client credentials grant

pkg/logging/scrubbingLogWriter.go, pkg/logging/scrubbingLogWriter_test.go
Moves the log scrubbing behaviour available in snyk-ls to the shared library. This is preparatory work for adopting this behaviour in the CLI. 
Original implementation: https://github.com/snyk/snyk-ls/blob/main/internal/logging/scrubbingLogWriter.go
Once this has been merged we can update https://github.com/snyk/snyk-ls/pull/424
=> feat: adds log scrubbing tool

pkg/analytics/analytics.go, pkg/analytics/analytics_test.go
Using the actual user.Current() during tests makes them more difficult to reproduce.
My username is `c`, which causes a lot of false positives; because each "c" substring gets replaced with "REDACTED", I can't run the tests locally as a result.
This makes `user.Current()` patchable, so that test scenarios can use a normalized, consistent "username".
=> chore: improve reproducibility of username sanitize tests

.circleci/config.yml, pkg/local_workflows/auth_workflow.go, pkg/mocks/networking.go, pkg/networking/networking.go, pkg/networking/networking_test.go, pkg/workflow/engine_test.go, pkg/workflow/engineimpl.go
This PR ensures to unset any available token when executing token authentication in auth_workflow.go
Therefore it adds cloning of the global NetworkAccess object before invoking an extension to avoid side effects between Extensions. This means that an Extension is even more sandboxed and will not affect global states or other Extension states.
To enable the CI/CD pipeline, I updated the runner image used to have a more recent golang version available.
=> fix: Authentication when using an invalid pre-existing token [HEAD-1197]

.golangci.yaml, internal/api/urls.go, pkg/local_workflows/output_workflow.go, pkg/logging/scrubbingLogWriter.go, pkg/networking/middleware/auth_header.go, pkg/utils/array.go
Fix issues flagged by the wastedassign rule.
Add a baseline golangci-lint configuration file. Not switching our build to use it yet though, because there are a lot of other rule violations to get through.
Planning to address each rule one-by-one, which will make for a more coherent, easy to read (and bisect) git commit history.
=> chore: golangci-lint fixes, wastedassign

pkg/analytics/analytics.go, pkg/auth/oauth2authenticator.go, pkg/auth/oauth2authenticator_test.go, pkg/configuration/constants.go, pkg/networking/networking_test.go
Several gosec linter fixes:
- Use secure random source for creating oauth2 verifer.
https://www.rfc-editor.org/rfc/rfc7636#section-4.1 prescribes a "high-entropy
cryptographic random [string]".
- nolint comments for sha1 usage, which is not ideal, but should not be a
security issue. Could be a future FedRAMP issue though...
- TLS listener test uses randomly assigned port and listens only on localhost.
This should avoid an annoying security pop-up on macOS. Also makes the test
more reproducible, in the event the dev machine has something listening on
8443.
- Satisfy slowloris warnings on http.Server setup without read timeouts.
Stacked on #119. PTAL at 39faa9faf90bf3bdf948952a47a1868ab6055258 if you want to review just the new changes introduced here.
CLI-49
=> chore: golangci-lint fixes, gosec

.circleci/config.yml, .golangci.yaml, Makefile, internal/api/api.go, internal/api/urls.go, internal/api/urls_test.go, internal/utils/temp-dir_test.go, pkg/analytics/analytics.go, pkg/analytics/analytics_test.go, pkg/app/app.go, pkg/auth/api_tokens.go, pkg/auth/oauth2authenticator.go, pkg/configuration/configuration.go, pkg/configuration/configuration_test.go, pkg/configuration/storage_test.go, pkg/local_workflows/auth_workflow.go, pkg/local_workflows/output_workflow.go, pkg/local_workflows/output_workflow_test.go, pkg/local_workflows/report_analytics_workflow.go, pkg/local_workflows/report_analytics_workflow_test.go, pkg/local_workflows/whoami_workflow.go, pkg/local_workflows/whoami_workflow_test.go, pkg/networking/certs/certs.go, pkg/networking/middleware/auth_header.go, pkg/networking/middleware/auth_header_test.go, pkg/networking/networking.go, pkg/networking/networking_test.go, pkg/workflow/dataimpl.go, pkg/workflow/dataimpl_test.go, pkg/workflow/engineimpl.go
Adding golangci-lint to the lint Makefile target, which means it will gate CI.
This PR is a little long, but I've tried to scope it down to a handful of rulesets whose changes are mechanical and generally low-risk (do not introduce significant logic changes, breaking API changes or refactoring).
I've also commented out the rules that I'd like to revisit in followups, especially the ones that will require careful review and possibly some discussion to address.
=> chore: enable golangci-lint

.golangci.yaml, internal/api/urls.go, pkg/analytics/analytics.go, pkg/analytics/analytics_test.go, pkg/app/app.go, pkg/auth/authenticator_test.go, pkg/auth/oauth2authenticator.go, pkg/auth/oauth2authenticator_test.go, pkg/configuration/configuration.go, pkg/configuration/configuration_test.go, pkg/configuration/storage_test.go, pkg/local_workflows/output_workflow.go, pkg/networking/certs/certs_test.go, pkg/networking/middleware/auth_header_test.go, pkg/networking/networking.go, pkg/networking/networking_test.go, pkg/workflow/dataimpl.go, pkg/workflow/engineimpl.go
Handle error return values to the greatest extent possible.
Ignore errcheck in areas where a breaking API change would be required, to be addressed in followups.
=> chore: satisfy lint errcheck rule

internal/api/api.go, internal/api/api_test.go, internal/api/contract/OrgFeatureFlagResponse.go, internal/mocks/api.go, pkg/app/app.go, pkg/app/app_test.go, pkg/configuration/constants.go, pkg/local_workflows/code_workflow.go
This PR adds a generic feature flag mechanism to the existing api client and uses this implementation to determine the value of a feature flag to enable a new code test workflow.
Currently the. feature flag only changes the log message but the test logic is the same.
=> feat: introduce feature flag for code test workflow

pkg/local_workflows/code_workflow.go, pkg/local_workflows/code_workflow_test.go
Add a pathway for iterating on a new Go based rendering using --json output of the TypescriptCLI
**Manually check**
* Build a fresh version of the CLI locally and run `./binary-releases/snyk-macos-arm64 code test --experimental`, you will get JSON output that matches `snyk code test --json`
=> feat: introduce --experimental for code extension

pkg/local_workflows/output_workflow.go, pkg/local_workflows/output_workflow_test.go
This will skip any inputs where the content type starts with the constant `CONTENT_TYPE_TEST_SUMMARY`. This will support potential future versioned test summary content types.
=> feat: skip test summary mime type

pkg/workflow/json_schemas/data_test_summary.go
Make it easier for consumers to work with this struct by introducing a named type for the Results data. 
```go 
// Define some sample TestSummaryResult structs
critical := TestSummaryResult{
Severity: "Critical",
Total:    10,
Open:     10,
Ignored:  0,
}
high := TestSummaryResult{
Severity: "High",
Total:    20,
Open:     17,
Ignored:  3,
}
// Instantiate the TestSummary struct
summary := TestSummary{
Type: "sbomz",
Results: [] TestSummaryResult{critical, high},
}
```
=> fix: expose TestSummaryResult struct

.gitleaksignore
Looks like the path was wrong for these ignores, not sure how it ever worked.
=> chore: update gitleaks ignore

go.mod, go.sum, pkg/local_workflows/code_workflow/code_client_helper.go, pkg/local_workflows/code_workflow/native_workflow.go
Updates the code-client-go library and picks up the logging improvements and function options pattern changes. We have also introduced a fallback instrumentor and error reporter so that the CLI doesn't need to create dummy ones. If you want to override them you can still do, but for now the fallbacks do exactly what the ones implemented here do.
=> refactor: use function options pattern

.gitleaksignore, internal/presenters/__snapshots__/presenter_sarif_results_pretty_test.snap, internal/presenters/components.go, internal/presenters/presenter_sarif_results_pretty.go, internal/presenters/presenter_sarif_results_pretty_test.go, internal/presenters/testdata/with-ignores.json, pkg/configuration/constants.go, pkg/local_workflows/output_workflow.go, pkg/local_workflows/output_workflow_test.go
Introduce support for hiding ignored items by default, this aligns with the current behaviour of the Typescript implementation. 
The new functionality here is to introduce 2 new flags `--include-ignores` and `--only-ignores` which can be used to toggle which items are displayed in the output. 
These screengrabs show the different flags and resulting output. 
By default we only show the open issues, there are four items visible:
Using `--include-ignores` will show also the ignored issue, there are now five items visible:
Using `--only-ignores` will only show the ignored issue(s), there is now one item visible:
=> feat: support --include-ignores flag

.gitleaksignore
It seems that due to the squash merge we have invalidated our `.gitleaksignore` file.
=> chore: ignore false positives

go.mod, go.sum, internal/api/api.go, internal/api/api_test.go, internal/api/contract/OrgResponse.go, internal/api/contract/UserMeResponse.go
This changes the API call to retrieve an org by slugname to the new endpoint at /rest/orgs
=> feat: use new API endpoint for org retrieval [IDE-221]

go.mod, go.sum, pkg/local_workflows/output_workflow_test.go
The LS can now upgrade to the latest code-client-go version, so that we return the real findings for repos from the Analysis API.
I will also update the CLI once https://github.com/snyk/snyk-ls/pull/497 is also merged.
=> feat: CLI renders real findings for consistent ignores

internal/api/api.go, internal/api/api_test.go, internal/api/contract/UserMeResponse.go, internal/constants/constants.go, internal/mocks/api.go, pkg/local_workflows/whoami_workflow.go, pkg/local_workflows/whoami_workflow_test.go
Replaced the legacy endpoint  /v1/user/me with the rest equivalent /rest/self in the whoami workflow
=> fix: replace legacy endpoint used by whoami

internal/presenters/components.go, internal/presenters/presenter_sarif_results_pretty.go, internal/presenters/presenter_sarif_results_pretty_test.go, pkg/configuration/constants.go, pkg/local_workflows/output_workflow.go, pkg/local_workflows/output_workflow_test.go
- **refactor: rename to remove typo**
- **feat: filter findings output to remove items outside of target severity**
- **fix: load severity-threshold from configuration**
- **feat: filter output by supplied severity threshold**
=> feat: support severity threshold

internal/presenters/__snapshots__/presenter_sarif_results_pretty_test.snap, internal/presenters/components.go, internal/presenters/presenter_sarif_results_pretty.go, internal/presenters/presenter_sarif_results_pretty_test.go, pkg/configuration/constants.go, pkg/local_workflows/output_workflow.go, pkg/local_workflows/output_workflow_test.go
After discussion we have decided **not** to support an `--only-ignores` flag in the initial release of this capability. We may introduce some filtering mechanism in the future but that work needs some further exploration to understand requirements.
=> fix: remove unused --only-ignores flag CLI-319

pkg/local_workflows/code_workflow/native_workflow.go, pkg/utils/file_filter.go, pkg/utils/file_filter_test.go
This PR should add support for `.snyk` style excludes when applying filtering rules for the `code_workflow`
To test locally:
- use local version of GAF in CLI `replace github.com/snyk/go-application-framework => ../../go-application-framework` in `go.mod`
- build a local cli binary `make clean build`
- add a `.snyk` file to repository that has a valid `excludes` section
- run local cli binary `<path/to/local/cli/binary> code test`
- validate that `.snyk` `excludes` are filtered
=> feat(code_workflow): support .snyk style excludes when applying filtering rules

internal/api/contract/UserMeResponse.go, pkg/local_workflows/whoami_workflow.go, pkg/local_workflows/whoami_workflow_test.go
This PR contains:
- refactoring of the tests for the whoami workflow and coverage for new rest API cases
- a fix for an edge case spotted during testing, when specifying --json output should also return name
=> test(whoami): refactor for rest api specific cases - CLI-21

pkg/utils/file_filter.go, pkg/utils/file_filter_test.go
This fixes an issue when trying to pass ignore files. The logic that selects the files to parse did not take into account filenames that contain ignore files. e.g. `somefile.gitignore.ts` will be parsed by the gitignore parser when it should not be
=> fix(file_filter): do not try and pass invalid ignore files

internal/presenters/__snapshots__/presenter_sarif_results_pretty_test.snap, internal/presenters/components.go
Small nit, ensure Test Summary title is rendered in bold text.
=> fix: add bold weight to summary output [CLI-311]

internal/presenters/__snapshots__/presenter_sarif_results_pretty_test.snap, internal/presenters/components.go
Note here that the Tip content should be indented to align with the title.
=> fix: left padding for tip content [CLI-311]

internal/presenters/__snapshots__/presenter_sarif_results_pretty_test.snap, internal/presenters/components.go, internal/presenters/presenter_sarif_results_pretty_test.go
When there are no ignores returned we should include a clear
label to state this rather than create ambiguity as to whether
something was broken.
=> feat: introduce empty state for ignores [CLI-311]

internal/presenters/__snapshots__/presenter_sarif_results_pretty_test.snap, internal/presenters/components.go, internal/presenters/presenter_sarif_results_pretty_test.go, internal/utils/sarif/sarif.go
Ensure that we show `0` counts for any severities where we found no vulnerabilities.
This improves the consistency of the interface and clearly communicates that we have found no known vulnerabilities. 
Note: Ignore the purple underline, that is an artefact of the screengrab process 🙈
=> fix: include zero count severities [CLI-311]

pkg/utils/file_filter.go, pkg/utils/file_filter_test.go
Handle errors when empty string is passed as target path.
=> fix: support empty path being passed to file_filter

internal/utils/is-ci-environment.go, internal/utils/is-ci-environment_test.go, pkg/analytics/analytics.go
Refactor isCiEnvironment check for usability and extend set of supported environments.
=> refactor: move is CI environment out for reuse [CLI-324]

pkg/analytics/categories.go, pkg/analytics/categories_test.go
This PR adds the `ParseCliArgs ` function to parse command-line arguments into product/command/flag categories as per the RFC.  The function uses whitelists and known commands to determine the correct categories, defaulting to "oss" if no product is explicitly provided.
=> feat(instrumentation): derive category vector CLI-307

pkg/analytics/analytics.go
First PR for CLI-325. 
We generate urn identifier and attach it as a header to the network requests.
=> feat(instrumentation): add interaction id header for network requests CLI-325

pkg/instrumentation/categories.go
Extended the list of known commands based on the [docs](https://docs.snyk.io/snyk-cli/cli-commands-and-options-summary).
=> fix(instrumentation): CLI-335 add missing known commands

go.mod, go.sum
Uses the new progress tracker factory and tracker from `code-client-go` in https://github.com/snyk/code-client-go/pull/49. It defaults to the noop tracker which does nothing.
To test:
- Run make build-debug in `snyk-ls` for the branch in https://github.com/snyk/snyk-ls/pull/514
- Add a `snyk-ls` and `go-application-framework` replace directive in the `go.mod` in `snyk`
- Run `make build` in `snyk`
=> feat: use progress tracker from code-client-go [IDE-222]

pkg/configuration/configuration.go, pkg/configuration/configuration_test.go, pkg/configuration/storage.go, pkg/local_workflows/auth_workflow.go
Authenticating with token (deprecated) or oauth causes different config keys to be written to the config store. If these are unset, it potentially leaves stale auth information in the config. This also makes it difficult to determine which auth information is being used during CLI interactions.
This change forces the authentication config to be either oauth or token (deprecated). If one is set, the other method's keys are unset.
This required the addition of a Configuration.Unset method. "Unset" is a long-sought after feature of spf13/viper, which will probably never be added by the maintainer, but it is fairly straightforward to implement in coordination with the config file storage.
=> feat: clear auth config keys when switching auth types

internal/presenters/__snapshots__/presenter_sarif_results_pretty_test.snap, internal/presenters/components.go
The behaviour prior to this change was indenting only the first line
where as we want the entire body of the tip to be indented.
=> fix: add padding for entire body of tip message

internal/presenters/__snapshots__/components_test.snap, internal/presenters/components.go, internal/presenters/components_test.go, pkg/ui/__snapshots__/consoleui_test.snap
The issue was mentioned [here](https://github.com/snyk/go-application-framework/pull/194#discussion_r1619071694) before but there seems to have been a regression.
This PR fixes the problem by copying the style before changing it and adding a test to detect a regression.
=> fix: line break in links

pkg/analytics/instrumentation_collector.go, pkg/analytics/instrumentation_collector_test.go, pkg/instrumentation/categories.go, pkg/instrumentation/categories_test.go
* When errors don't have an id, don't add empty error structures to the serialized data
* ensure category vector is lower case
* add GetDuration()
=> fix: empty errors in serialized instrumentation data

pkg/local_workflows/json_schemas/schemas.go, pkg/local_workflows/report_analytics_workflow.go, pkg/local_workflows/report_analytics_workflow_test.go
This fix changes the behaviour of the analytics report workflow to convert v1 data and send it directly. This change is necessary to work in VS and IntelliJ, since a previous assumption didn't work out.
=> fix: Sending behaviour in analytics report workflow

pkg/instrumentation/categories.go, pkg/instrumentation/categories_test.go, pkg/instrumentation/instrumentation.go, pkg/instrumentation/instrumentation_test.go, pkg/instrumentation/test/instrumentation_public_test.go
By introducing the convenience method, we can reduce the public API as well.
=> chore: Introduce GetCategory() convenience method

pkg/local_workflows/report_analytics_workflow.go, pkg/local_workflows/report_analytics_workflow_test.go
IDEs send app name and version as the IDE name, which makes it redundant, as the same info is in the environment. This PR ensures to keep CLI version information.
=> fix: use cli runtime info when translating v1 data

pkg/networking/middleware/auth_header.go, pkg/networking/middleware/auth_header_test.go
Wrap authentication failure errors with ErrAuthenticationFailed so that callers of NetworkAccess.AddHeaders can match this particular error condition: whether headers failed to add due to an authentication failure.
CLI-392
=> feat: wrap authentication error for matching

pkg/networking/networking.go, pkg/networking/networking_test.go
For certain error status codes the http response body was logged in trace level. The faulty implementation consumed the body data and left no data for subsequent consumers. 
* The fix is to assign a buffer reader to the body when logging it's content.
* We also changed the status codes for which we log to >= 400
=> fix: incorrect handling of http response body when trace level logging

pkg/configuration/storage.go, pkg/configuration/storage_test.go
In some cases the settings file exists but it doesn't have any content.
I'm not sure why this happens.
Nonetheless I changed the Set func to check if file has no content. 
If it doesn't it will set it as empty json so that it won't fail on deserialize
=> fix: config persistence when config file is empty

pkg/auth/oauth2authenticator.go
Openbrowser on linux starts a new process and uses os.Stdout for Stdout by default. Which messes up the JRPC stream in LS.
Causing LS to crash
=> fix: redirect stdout to stderr for browser pkg

Makefile, internal/cueutils/convert/to_cli/from_testapi.cue, internal/cueutils/convert/to_testapi/from_cli_test_managed.cue, internal/cueutils/schemas/cli_test_managed.cue, internal/cueutils/schemas/v1_test_dep_graph.cue
Update to the project's build system and linting tools.
**Changes:**
* **Formatting:** Added `cue fmt` command to format `.cue` files within the `internal/cueutils` directory.
* **Linting:**
* Added `cue` as a linting tool alongside `golangci-lint`.
* Updated `lint` target to include linting `.cue` files with `cue fmt --all-errors --check`.
* **Dependencies:** Added installation instructions for `cue` within the `tools` target.
**Benefits:**
* Improved code formatting consistency for `.cue` files.
* Enhanced code quality by adding linting support for `.cue` files.
**Testing:**
Please review the changes and verify that the build process and linting continue to function as expected.
**Additional Notes:**
* The diff shows specific changes made to the `Makefile` and relevant `.cue` files …
=> chore: introduce formatting and lint for cuelang

.circleci/config.yml, go.mod, internal/cueutils/transformer.go, internal/cueutils/transformer_unix.go, internal/cueutils/transformer_windows.go, internal/presenters/presenter_local_finding_test.go, pkg/local_workflows/data_transformation_workflow_test.go
Embedded cue module is loaded with a custom loader that resolves absolute paths, even though the paths are "virtual".
Adding a drive-letter seems to resolve problems with this when running on a Windows OS.
CLI-514
=> fix: windows support for cueutils

.circleci/config.yml, Makefile, pkg/configuration/storage_test.go
Add race detector to unit tests, go test ./... -race
Remove t.Parallel() from tests which operate on the same config file and potentially mutate and check the same key.
This fixes a data race in which a map loaded from a config file was concurrently accessed inappropriately in previously parallel tests.
It also removes an unstable test setup condition. "File contains key" was potentially in conflict with "Overwrites existing value" in Test_JsonStorage_Set_ConfigFileHasValues, even if storage.Set is mutually exclusive.
=> chore: use race detector for unit tests

pkg/configuration/configuration.go, pkg/configuration/configuration_test.go, pkg/networking/networking_test.go, pkg/workflow/engine_test.go
This PR makes changes so that environment variables that are supported by GAF are configurable as opposed to GAF automatically detecting supported environment variables.
=> fix: only read supported env vars (CLI-526)

go.mod, go.sum, internal/constants/constants.go, internal/presenters/__snapshots__/components_test.snap, internal/presenters/components.go, internal/presenters/components_test.go, pkg/ui/__snapshots__/consoleui_test.snap
- Updates the dependency for the Error Catalog.
- Includes the description field in the RenderError output for errors from the Error Catalog, shortening the field to the first 2 paragraphs in case of longer descriptions. 
- Changed the label for the HTTP status and added the status code text next to the value.
- Changed the label for the links and added a default link for the error catalog page when the error code is present.
- Renders the title without the parentheses in case of no defined error code.
Ticket: [CLI-551](https://snyksec.atlassian.net/browse/CLI-551)
[CLI-551]: https://snyksec.atlassian.net/browse/CLI-551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: render description for Error Catalog errors

pkg/local_workflows/data_transformation_workflow.go, pkg/local_workflows/filter_workflow.go, pkg/local_workflows/output_workflow.go, pkg/local_workflows/output_workflow/constants.go, pkg/local_workflows/output_workflow/findings_model_tools.go, pkg/local_workflows/output_workflow_test.go
The use case for parallel rendering of the same findings models is for example when the writer differ, like writing to a file and stdout, as it is currently supported.
=> chore: Support rendering findings models multiple times in parallel

pkg/local_workflows/config_utils/sanitycheck.go, pkg/local_workflows/config_utils/sanitycheck_test.go
Adjust the wording for the config check to make it easier to understand. 
[CLI-564]
[CLI-564]: https://snyksec.atlassian.net/browse/CLI-564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: clarify wording on config check failure

pkg/instrumentation/categories.go, pkg/instrumentation/categories_test.go
The current implementation was missing the default product for monitor commands.
=> fix: add default oss product for monitor as well

internal/utils/convert.go, pkg/app/app.go, pkg/configuration/configuration.go, pkg/configuration/configuration_test.go, pkg/local_workflows/code_workflow.go, pkg/local_workflows/config_utils/feature_flag.go, pkg/mocks/configuration.go, pkg/mocks/networking.go, pkg/networking/middleware/response.go, pkg/networking/middleware/response_test.go, pkg/networking/network_types/error_handler.go, pkg/networking/networking.go, pkg/networking/networking_test.go
- Adds a new method to the NetworkAccess interface for registering an error handler
- Implements the handler for 401 unauthorized status code
Ticket: [CLI-575](https://snyksec.atlassian.net/browse/CLI-575)
[CLI-575]: https://snyksec.atlassian.net/browse/CLI-575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: handle non 2xx responses in GAF network stack

pkg/logging/scrubbingLogWriter.go, pkg/logging/scrubbingLogWriter_test.go
When reviewing the logic of the scrubbing log writer, I found that level and io writer have a slightly different error handling.
=> fix: adapting inconsistent logic in scrubbing log writer

pkg/auth/oauth2authenticator.go
This adds `cross_region_routing=true` to the `oauth2/authorize` query.
=> chore: add cross-region-routing flag

pkg/local_workflows/whoami_workflow.go
This will enable a feature to write data temporary to disk for data originating from the whoami workflow. This is based on a threshold, which will normally not be triggered by whoami, but it'll make testing in the CLI much easier and less flaky.
=> chore: use configuration when creating data

pkg/local_workflows/output_workflow.go, pkg/local_workflows/output_workflow/constants.go, pkg/local_workflows/output_workflow/findings_model_tools.go, pkg/local_workflows/output_workflow/findings_model_tools_test.go
In some situations the output workflow might not be required to create a file if there is no or no actual data given, for example when the list of findings is empty, it might not make sense to write a sarif file.
The example behaviour is a specific behaviour of the legacy CLI and is therefore considered a configuration option.
=> feat: introduce option to disable creating empty sarif files

pkg/networking/middleware/response.go, pkg/utils/errors.go, pkg/utils/errors_test.go
**Changes:**
- The `AddMetaDataToErr` function now uses the `snyk_errors.WithMeta` helper function to add metadata to errors. This ensures a consistent approach to metadata handling and avoids potential issues with direct map manipulation.
- Added tests to verify the correct behavior of `AddMetaDataToErr`, including handling different error types and ensuring that the original error is not modified.
- Moves `AddMetaDataToErr` out to generic utils/error directory. 
Benefits:
- Improved consistency: Metadata is now added using a dedicated helper function, ensuring a standardized approach across the codebase.
- Reduced risk of errors: Using `WithMeta` eliminates potential issues with directly modifying the `Meta` map, such as accidentally overwriting existing metadata.
- Enhanced …
=> chore: refactor to use exposed method

pkg/logging/scrubbingLogWriter.go, pkg/logging/scrubbingLogWriter_test.go
The change introduces partial writes of the underlying logger used by the scrubbing logger. Previously partial writes would have caused a loss of log information.
=> fix: Fix handle partial writing of debug logs

pkg/configuration/constants.go, pkg/local_workflows/code_workflow.go, pkg/local_workflows/code_workflow/native_workflow.go, pkg/local_workflows/code_workflow_test.go
- Adds a new feature flag that enables the usage of the native code workflow even if the CCI flag is not enabled
- Removes the usage of the report flag from deciding when to use the native implementation
[CLI-775](https://snyksec.atlassian.net/browse/CLI-775)
[CLI-775]: https://snyksec.atlassian.net/browse/CLI-775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: update native code test feature flags

pkg/logging/scrubbingLogWriter.go, pkg/logging/scrubbingLogWriter_test.go
This PR adds an additional redact rule to the scrubbing logger to redact the os username.
=> chore: redact the username when scrubbing logs

internal/utils/file.go, internal/utils/file_test.go, pkg/local_workflows/output_workflow.go, pkg/local_workflows/output_workflow/findings_model_tools.go, pkg/local_workflows/output_workflow/findings_model_tools_test.go, pkg/local_workflows/output_workflow_test.go
This PR ensures that if output files are specified, missing folders are being created, so that the file can be written.
=> fix: Ensure to create folders for outputfile

pkg/analytics/instrumentation_collector.go, pkg/analytics/instrumentation_collector_test.go, pkg/local_workflows/report_analytics_workflow.go
In https://github.com/snyk/cli/pull/5813 we are going to pass the legacy v1 analytics to the new analytics service, utilizing the `extension` attribute in the payload.
Since the extension payload can be used by all product lines, it would be good practice to ensure proper PII protection of that part of the payload.
Further, since the `v1` data is already passed through that sanitation logic, it makes sense to do the same to the data when passed to the analytics service.
I also re-wrote the test a tad to make each test independent of the other, as some test runners were mutating the assertion object. Also a tendency to flakiness as timestamps were being compared.
=> fix: [CLI-841] redacting extension endpoint of instrumentation payload

internal/api/api.go, internal/mocks/api.go, pkg/local_workflows/code_workflow.go
use pointer for sastResponse and returning nil instead of empty structs.
=> fix: use pointer for sastResponse and returning nil instead of empty [IDE-724]

pkg/networking/logging.go, pkg/networking/logging_test.go, pkg/networking/networking.go, pkg/networking/networking_test.go
* This PR includes a fix where network logging was only available on debug level, trace level disabled it completely
* This PR extends the debug level logging of network requests to include request and response bodies in trace level logging. Response bodies continue to be logged in debug level logging when the response status code > 400.
=> chore: extend network trace level debug logs to include request and response bodies

go.mod, go.sum, pkg/local_workflows/ignore_workflow/config.go, pkg/local_workflows/ignore_workflow/ignore_workflow.go
Some small changes for the CLI RC regarding the ignore workflow.
- replace the feature flag error with the error catalog equivalent
- rename the `--id` parameter to `--finding-id` for better clarity 
- remove the interactive prompt for the `expiry` if the flag is not set
- [CLI-IDE sync notes](https://snyksec.atlassian.net/wiki/spaces/CLI/pages/3215982961/IAW+Sync+CLI+IDE#28.04.2025)
=> chore: update ignore workflow

pkg/networking/middleware/response.go, pkg/networking/middleware/response_test.go
We're implementing a change in how we handle network requests from the Legacy CLI in order to avoid writing the same logic for both the GAF network stack and the proxied requests from the Legacy CLI.
This requires us to keep the response object from the RoundTripper even on errors, which is a bit unidiomatic, but the best compromise I could find.
Currently, if our `RoundTrip()` logic fails on an error, we do not return the raw response, but only the error (which is probably correct), but in order for us to handle the errors from the legacy CLI correctly, we need to preserve the raw HTTP error and handle it later in the stack.
Relevant details from the dependent [CLI PR](https://github.com/snyk/cli/pull/5888):
> The relevant downstream logic is found in the `goproxy` …
=> fix: [CLI-888] allowing populated response in RoundTrip error cases

go.mod, go.sum, pkg/app/app.go, pkg/networking/middleware/retry_middleware.go, pkg/networking/middleware/retry_middleware_test.go, pkg/networking/networking.go
This PR introduces a retry middleware and adds it to the default network stack. Per default retries are disabled and the middleware will act as a pass through, but for `preview` versions and if the feature is enabled, network requests failing with a certain status code will automatically be retried.
This can be enabled for example in the CLI by setting the environment variable `INTERNAL_NETWORK_REQUEST_MAX_ATTEMPTS=<N>`, where <N> is the maximum number of request attempts, 1 being the minimum.
The Status Codes that will be retried can be found [here](https://github.com/snyk/go-application-framework/pull/346/files#diff-295d20b71bb7f7fdc47d3503d7fb17595142bb2c48dd5801cc4ad0517afb1a55R26)
There are some changes/improvement that are left for future iterations, like optimizations around memory …
=> feat: Introduce retry middleware

internal/cueutils/source/sarif-schema-2.1.0.json, internal/presenters/templates/local_finding.sarif.tmpl, pkg/local_workflows/testdata/sarif-snyk-goof-ignores.json
Picked up the changes from #343, just updates the SARIF schema link to the latest errata version. 
Ref: [CLI-470](https://snyksec.atlassian.net/browse/CLI-470)
[CLI-470]: https://snyksec.atlassian.net/browse/CLI-470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: update SARIF schema link to the latest 2.1.0 version

pkg/apiclients/mocks/testapi.go, pkg/apiclients/testapi/mock_server_test.go, pkg/apiclients/testapi/testapi.go, pkg/apiclients/testapi/testapi_test.go
- [DGP-434] Add accessors for all of the API spec's test results.
- Updates tests, moving much of the setup into a helper function.
One consideration was returning the entire TestAttrs struct from the test API codegen but that would leave end-user code brittle to API spec changes, and buries some of the key attributes, like PassFail.  The getter approach gives us an abstraction layer for making internal changes non-breaking.  However, flattening every field into a Getter doesn't leave a good experience because related fields would not be grouped together -- to group related fields we'd have names like OutcomeBreachedPolicyIds and OutcomeBreachedPolicyLocalPolicy.  The approach taken is to have Getters that flatten key items at the top level (like the Outcome struct's PassFail, and State's …
=> feat: [DGP-434] add accessors for all of the API spec's test results

pkg/workflow/analyticsWrapper_test.go
Explicitly set the duration value in the analyticswrapper test, since using the actual duration in a test adds flakiness.
=> fix: add explicit duration value to reduce flakiness

pkg/utils/file_filter.go, pkg/utils/file_filter_test.go
This PR fixes a bug where the file filter incorrectly interpreted the `/` pattern in `.gitignore` files. The current implementation treats `/` as `/**`, which causes it to ignore all files in the directory tree. However, according to Git's actual behavior, a single `/` pattern has no effect.
When a `.gitignore` file contains just `/`, the file filter was:
- Converting it to `{baseDir}/**` 
- This matches everything in the directory tree
- All files were being ignored (filtered out)
However, Git's actual behavior is:
- `/` pattern has **no effect** 
- `/*` pattern ignores everything
Added special case handling in `parseIgnoreRuleToGlobs` to return empty globs when the rule is exactly `/`. This makes the Snyk file filter behavior consistent with Git.
Added comprehensive tests to verify:
- …
=> fix: handle single slash pattern correctly in gitignore [IDE-1257]

pkg/local_workflows/code_workflow.go, pkg/local_workflows/config_utils/experimental.go, pkg/local_workflows/config_utils/experimental_test.go, pkg/local_workflows/connectivity_check_extension/connectivity_check_workflow.go, pkg/local_workflows/whoami_workflow.go
This PR adds helper functions to create and check experimental workflows. It also shifts away from the need to check experimental in extensions and mainly leaves it to the application to enforce it though the given helpers.
=> chore: Introduce unified experimental handling

pkg/app/app.go, pkg/configuration/configuration.go, pkg/configuration/configuration_test.go, pkg/local_workflows/code_workflow.go, pkg/local_workflows/config_utils/feature_flag.go, pkg/local_workflows/ignore_workflow/config.go
BREAKING CHANGE: extends the method signature for configuration.DefaultValueFunction to accept configuration.Configuration as the first parameter
=> fix: defaultFns accept config as a parameter

go.mod, go.sum, internal/api/api.go, internal/api/contract/OrgSettingsResponse.go, internal/mocks/api.go, pkg/local_workflows/ignore_workflow/config.go, pkg/local_workflows/ignore_workflow/ignore_workflow.go, pkg/local_workflows/ignore_workflow/ignore_workflow_test.go
Previously, the IAW create workflow was gated behind a feature flag check. For EA, customers should be able to opt in/out of using the ignore approval, so a new org setting was added for them to toggle on/off. 
This PR just swaps out the feature flag check with an fetching the org settings and checking whether IAW is enabled for the current org before proceeding with the ignore create workflow.
Ref: [CLI-1006](https://snyksec.atlassian.net/browse/CLI-1006)
[CLI-1006]: https://snyksec.atlassian.net/browse/CLI-1006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: iaw uses org setting insted of feature flag

pkg/app/app.go, pkg/app/app_test.go
This fix adds sanitization of a user defined input directory to avoid issues based on unexpected inputs like empty strings.
=> fix: Increase tolerance for invalid input directories

pkg/instrumentation/categories.go, pkg/instrumentation/instrumentation.go, pkg/instrumentation/instrumentation_test.go, pkg/logging/scrubbingLogWriter.go, pkg/logging/scrubbingLogWriter_test.go
This PR updates our log scrubbing implementation to a more layered approach. Where we initially only relied on regex pattern matching to scrub sensitive data from our logs, we will now also pass in known parameters for scrub processing.
Unknown parameters will be scrubbed, whilst known parameters are not.
=> fix(logging): base sanitisation of logs on known parameter values

go.mod, go.sum
Updating to new code-client-go version based on https://github.com/snyk/code-client-go/pull/123
=> fix: forward project and snapshot id to local findings

internal/presenters/funcs.go, internal/presenters/presenter_local_finding_test.go, internal/presenters/templates/local_finding.sarif.tmpl
Updates the presenters to include the `runAutomationDetails` [id](https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/os/sarif-v2.1.0-errata01-os-complete.html#_Toc141790776) field in the SARIF output for the native code implementation.
=> feat: add runAutomationsDetailsId for SARIF output
